sudo: required

language: generic
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - PYTHON=2.7
        - MODIN_ENGINE=ray
      after_success:
        - bash < (curl -s https://codecov.io/bash)

    - os: linux
      dist: trusty
      env:
        - PYTHON=3.6
        - MODIN_ENGINE=ray
      after_success:
        - bash < (curl -s https://codecov.io/bash)

    - os: linux
      dist: trusty
      env: 
        - PYTHON=2.7
        - MODIN_DEBUG=1
      after_success:
        - bash < (curl -s https://codecov.io/bash)

    - os: linux
      dist: trusty
      env: 
        - PYTHON=3.6
        - MODIN_DEBUG=1
      after_success:
        - bash < (curl -s https://codecov.io/bash)

    - os: linux
      dist: trusty
      env: 
        - LINT=1
      script:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - black --check modin/
        - flake8 .

install:
  - ./.travis/install-dependencies.sh

script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if [[ "$PYTHON" == "2.7" ]]; then python .travis/strip-type-hints.py; fi
  - python -m pytest -n auto --disable-pytest-warnings modin/pandas/test/test_dataframe.py --cov-config=.coveragerc --cov=modin modin/pandas/test/
  - python -m pytest --disable-pytest-warnings modin/pandas/test/test_concat.py --cov-config=.coveragerc --cov=modin modin/pandas/test/
  - python -m pytest --disable-pytest-warnings modin/pandas/test/test_io.py --cov-config=.coveragerc --cov=modin modin/pandas/test/
  - python -m pytest --disable-pytest-warnings modin/pandas/test/test_groupby.py --cov-config=.coveragerc --cov=modin modin/pandas/test/
  - python -m pytest --disable-pytest-warnings modin/experimental/pandas/test/test_io_exp.py --cov-config=.coveragerc --cov=modin modin/pandas/test/
