name: Modin_CI_Master_Build
on: push
jobs:
  testmon:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6.x"
          architecture: "x64"
      - run: sudo apt install -y libhdf5-dev
      - run: pip install -r requirements.txt
      - run: MODIN_ENGINE=ray python -m pytest modin/pandas/test/
      - run: MODIN_ENGINE=python python -m pytest modin/pandas/test/
      - run: MODIN_ENGINE=dask python -m pytest modin/pandas/test/test_io.py
      - run: MODIN_BACKEND=pyarrow python -m pytest modin/pandas/test/test_io.py::test_from_csv
      - uses: actions/upload-artifact@v1
        with:
          name: .testmondata
          path: .testmondata
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6.x", "3.7.x"]
        engine: ["python", "ray"]
        part: [1, 2, 3]
    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      PYTEST_ADDOPTS:  "--cov-config=.coveragerc --cov=modin  --cov-append"
    name: test (${{matrix.engine}}, part ${{matrix.part}}, python ${{matrix.python-version}})
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python-version}}
          architecture: "x64"
      - run: sudo apt install -y libhdf5-dev
      - run: pip install -r requirements.txt
      - run: export MODIN_ENGINE=${{matrix.engine}}
      - run: python -m pytest -n auto modin/pandas/test/test_dataframe.py::TestDFPartOne
        if: matrix.part == 1
      - run: python -m pytest -n auto modin/pandas/test/test_dataframe.py::TestDFPartTwo
        if: matrix.part == 2
      - run: python -m pytest modin/pandas/test/test_series.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_concat.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_groupby.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_reshape.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_general.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_io.py
        if: matrix.part == 3
      - run: python -m pytest modin/experimental/pandas/test/test_io_exp.py
        if: matrix.part == 3
      - run: bash <(curl -s https://codecov.io/bash)
  test-windows:
    needs: [lint-flake8, lint-black]
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.6.x", "3.7.x"]
    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      MODIN_ENGINE: dask
    name: test dask
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python-version}}
          architecture: "x64"
      - run: pip install -r windows_test_requires.txt
      - run: python -m pytest modin/pandas/test/test_io.py
      - run: choco install codecov
      - run: codecov -f .\coverage.xml -t ${{secrets.CODECOV_TOKEN}}
  test-pyarrow:
    needs: [lint-flake8, lint-black]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6.x", "3.7.x"]
    env:
      MODIN_BACKEND: pyarrow
      MODIN_EXPERIMENTAL: "True"
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    name: test (pyarrow, python ${{matrix.python-version}})
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python-version}}
          architecture: "x64"
      - run: sudo apt install -y libhdf5-dev
      - run: pip install -r requirements.txt
      - run: python -m pytest modin/pandas/test/test_io.py::test_from_csv
      - run: bash <(curl -s https://codecov.io/bash)
  test-api:
    needs: [lint-flake8, lint-black]
    runs-on: ubuntu-latest
    name: test api
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
          architecture: "x64"
      - run: sudo apt install -y libhdf5-dev
      - run: pip install -r requirements.txt
      - run: python -m pytest modin/pandas/test/test_api.py
